Review
Biokarl/stellar-burgers pull request #1
Opened 2024-08-07 15:59 UTC by Biokarl

2024-08-07 20:12 UTC, SergeyK2004 requested changes
Что сделано отлично:
Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модально окно. Весь заявленный функционал реализован. Здорово, что выделяется активная страница в главном меню. Бургер корректно собирается с возможностью менять ингредиенты местами.

Что нужно исправить:

* https://disk.yandex.ru/d/rbJCl50Mh7YtBA  Булка в заказе должна присутствовать в количестве 2 штук.
* На странице профиля в истории заказов, пользователь должен видеть только свои заказы. Сейчас видно все заказы из ленты заказов.
* https://disk.yandex.ru/d/c9DW1tIQ8JYGdQ Нужно центрировать контент на странице с деталями ингредиента.
* В createAsyncThunk не нужно указывать блок catch, так как createAsyncThunk сам ловит ошибки и отображает их в поле rejected. А его уже обрабатывать можно в createSlice

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 
Напоминаю, что работа может быть принята только после исправления всех критических замечаний Нужно исправить.
Удачного рефакторинга кода.

2024-08-07 20:12 UTC, SergeyK2004 commented on src/slices/burgerConstructorSlice.ts
> +        payload: { ...item, id: nanoid() }
Отлично: 

Правильно, что работу с библиотекой вы вынесли в prepare

2024-08-07 20:12 UTC, SergeyK2004 commented on src/slices/feedSlice.ts
> +  } catch (error) {
Надо исправить:

В createAsyncThunk не нужно указывать блок catch, так как createAsyncThunk сам ловит ошибки и отображает их в поле rejected. А его уже обрабатывать можно в createSlice

2024-08-07 20:12 UTC, SergeyK2004 commented on src/components/app/app.tsx
> +        <Routes location={backgroundLocation || location}>
Отлично

Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модально окно

2024-08-09 07:07 UTC, SergeyK2004 approved these changes
Отлично. Поздравляю со сдачей проекта. Желаю успехов в дальнейшем обучении.

2024-09-04 13:45 UTC, kyzinatra commented on cypress/e2e/constructor.cy.ts
> +  );
Можно лучше: так как вы мокаете токены, то их можно выбрать совсем любые. К примеру

```js
 setCookie(
    'accessToken','accessToken'
  );

```

2024-09-04 13:45 UTC, kyzinatra commented on cypress/e2e/constructor.cy.ts
> +    cy.intercept('POST', '**/api/orders', {
Отлично! Круто, что вы комментруете тесты

2024-09-04 13:48 UTC, kyzinatra commented on src/slices/__tests__/burgerConstructorSlice.jest.ts
> +    fat: 2,
Можно лучше: такие константы лучше вынести отдельно, чтобы каждый раз их не копипастить, так как это усложняет чтение кода

2024-09-04 13:50 UTC, kyzinatra commented on src/slices/__tests__/user.jest.ts
> +        initialState,
Можно лучше: обычно принято указывать в названии теста что он должен сделать. К примеру `Должен активироваться статус ожидания регистрации`

2024-09-04 13:53 UTC, kyzinatra commented on src/slices/__tests__/ingredients.jest.ts
> +    const state = reducer(
Надо исправить: необходимо также добавить проверку начального состояния для всех редьюсеров (или 1 проверку, но всего стора), по аналогии с `order slice`

2024-09-04 13:54 UTC, kyzinatra commented
Выглядит очень круто! Видно, что проделана большая работа. Но все же есть моменты на которые стоит обратить внимание.
Подробнее: 

**Что важно исправить:**

-  необходимо также добавить проверку начального состояния для всех редьюсеров (или 1 проверку, но всего стора), по аналогии с `order slice`


**Можно лучше:**

-  так как вы мокаете токены, то их можно выбрать совсем любые. К примеру

```js
 setCookie(
    'accessToken','accessToken'
  );

```

-  обычно принято указывать в названии теста что он должен сделать. К примеру `Должен активироваться статус ожидания регистрации`


**Что понравилось:**

-  Круто, что вы комментруете тесты
-  Понравилось, что вы испольузете `intercept`
-  Круто, что вы проверяете начальное состояние


**Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.**

2024-09-05 05:33 UTC, kyzinatra approved these changes
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2025-01-20 20:15 UTC, merged